### ISSUE TITLE
OpenColorIO is missing use cases.

### ISSUE THREAD

**Issue by andymanaws** [aws-deadline/deadline-cloud-for-nuke#141]
### Use Case

Currently the submitter and adaptor only captures a specific use case - a custom config file for OCIO.

There are other use cases:
- the OCIO environment variable is used to specify the config file.
- the customer is using OCIO, but it defaulting to a stock config file ( but we must make the assumption that just because it resides in an install location, that it hasnt been manipulated away from its default value).

### Proposed Solution

Add more methods to the submitter to find the OCIO config file
1> Query the environment for OCIO and use that if is exists.
2> Query is the user is utilising a config from the found search paths already available on their system( and explicitly add that).
3> Potentiall store in the template that the scene was being driven by an OCIO environment vaiablr.
4> Check that the config file specified in the above is actually a file ( additional alert for malformed OCIO environments, and to prevent a submitter crash).

add more methods to the adaptor:
1> Add the search paths for not just custom config file setups.
2> If the user has elected use an OCIO environment variable, set that OCIO environment variable with the stashed job attachment.( again this might need an update to the submitter - as this is external to Nuke at submission time, and the scene wont store this info).

**Comment by crowecawcaw** [comment]
Added in this PR: https://github.com/aws-deadline/deadline-cloud-for-nuke/pull/166
